/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.mycompany.data_project_culminating;

/**
 *
 * @author irolu9768
 */
public class User_Interface1 extends java.awt.Frame {

    /**
     * Creates new form NewFrame
     */
    public User_Interface1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar1 = new java.awt.MenuBar();
        Home1 = new java.awt.Menu();
        Testing1 = new java.awt.Menu();
        Learn = new java.awt.Menu();
        Help = new java.awt.Menu();

        jToolBar1.setRollover(true);

        setBackground(java.awt.Color.darkGray);
        setMaximizedBounds(new java.awt.Rectangle(1, 1, 2, 2));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setLayout(new javax.swing.BoxLayout(jDesktopPane1, javax.swing.BoxLayout.LINE_AXIS));

        Home1.setLabel("Home ");
        Home1.setName("");
        Home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home1ActionPerformed(evt);
            }
        });
        menuBar1.add(Home1);
        Home1.getAccessibleContext().setAccessibleParent(jDesktopPane1);

        Testing1.setLabel("Testing");
        Testing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Testing1ActionPerformed(evt);
            }
        });
        menuBar1.add(Testing1);

        Learn.setLabel("Learning");
        menuBar1.add(Learn);

        Help.setLabel("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        menuBar1.add(Help);

        setMenuBar(menuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);  
        
    }//GEN-LAST:event_exitForm

    private void Testing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Testing1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Testing1ActionPerformed

    private void Home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home1ActionPerformed
        // TODO add your handling code here: 
       
    }//GEN-LAST:event_Home1ActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Interface1().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Menu Help;
    private java.awt.Menu Home1;
    private java.awt.Menu Learn;
    private java.awt.Menu Testing1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
